Migrate Catch2 from v2 to v3
autodiff/autodiff pull request #248
Opened 2022-08-24 09:37 UTC by RMeli

This PR migrates Catch2 from v2 to v3, following the [migration instructions](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top).

@allanleal Catch is also used in `test/BUILD`. I see in the [installation instructions](https://autodiff.github.io/installation/) that this is for the [Bazel](https://bazel.build/) build system. I never used it before and I can't see it in the CI builds; is there any documentation related to `autodiff` about this?

Fix #246

2022-08-24 11:29 UTC, allanleal commented
Hi @RMeli , I work with CMake only. Bazel support was provided in the past by a contributor. There is no Bazel installation instructions at the moment (https://autodiff.github.io/installation/).

2022-08-24 11:32 UTC, allanleal requested changes

2022-08-24 11:32 UTC, allanleal commented on tests/reverse/var/var.test.cpp
> +    using autodiff::derivatives;
```suggestion
using autodiff::derivatives;
```

2022-08-24 11:32 UTC, allanleal commented on tests/CMakeLists.txt
> -add_custom_target(tests
We need the target `tests`, which is used in the CI (e.g., `ninja tests`). This code here removes it.

2022-08-24 11:57 UTC, RMeli commented
> I work with CMake only. Bazel support was provided in the past by a contributor.

I see. I will try to wrap my head around it.

2022-08-24 21:18 UTC, RMeli commented
@allanleal, is `bazel` integration updated at all since you work with CMake and it does not seem to be used in CI? I just tried to run `bazel test //...` (as suggested in https://github.com/autodiff/autodiff/pull/126#issuecomment-699948239) on the `main` branch, and I obtained the following error:
```
INFO: Analyzed 27 targets (2 packages loaded, 33 targets configured).
INFO: Found 4 targets and 23 test targets...
ERROR: /Users/rmeli/Documents/git/software/autodiff/examples/forward/BUILD:85:8: Compiling examples/forward/example-forward-gradient-derivatives-using-eigen-with-scalar.cpp failed: missing input file '//examples/forward:example-forward-gradient-derivatives-using-eigen-with-scalar.cpp'
ERROR: /Users/rmeli/Documents/git/software/autodiff/examples/forward/BUILD:85:8: Compiling examples/forward/example-forward-gradient-derivatives-using-eigen-with-scalar.cpp failed: 1 input file(s) do not exist
ERROR: /Users/rmeli/Documents/git/software/autodiff/examples/forward/BUILD:85:8 Compiling examples/forward/example-forward-gradient-derivatives-using-eigen-with-scalar.cpp failed: 1 input file(s) do not exist
INFO: Elapsed time: 0.247s, Critical Path: 0.02s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

Looking at
https://github.com/autodiff/autodiff/blob/64346ae42b4a82cdefb364d289ebe5479cadc12c/examples/forward/BUILD#L85-L90
it seems that the paths are not up to date, since there is no `example-forward-gradient-derivatives-using-eigen-with-scalar.cpp` in `autodiff/examples/forward/`.

Manually updating the `cc_test` entries solves the issue. I haven't yet figured out how to use Catch2 v3 with `bazel` (all examples I could find use Catch2 v2), but I was wondering if it is worth the effort if `bazel` integration is not maintained? Any thoughts/suggestions here?

2022-08-25 06:55 UTC, allanleal commented
@RMeli , thanks a lot for investigating the current status of Bazel support in the project.

> but I was wondering if it is worth the effort if bazel integration is not maintained? Any thoughts/suggestions here?

This will depend on community help. Unfortunately I cannot maintain bazel support in autodiff (too much on my plate already). 

I'm pinging @patrickhart and @markisus who in the past made contributions in this regard. Guys, would you kindly help us here? It would be good to have bazel builds in the CI so that we know that it has not been broken with changes in the lib.

2022-08-25 06:57 UTC, allanleal commented
@RMeli , all looks good to me. Can we merge this?

2022-08-25 07:34 UTC, RMeli commented
>  Unfortunately I cannot maintain bazel support in autodiff (too much on my plate already).

I totally get it! Unfortunately, I don't have the knowledge nor the time to take care of that either.

> @RMeli , all looks good to me. Can we merge this?

I converted to a draft to investigate how to update `bazel`. If further divergence with `bazel` is not a concern here (since it's already not working, should I open a separate issue for the record?), I'm happy to merge.

2022-08-25 07:36 UTC, RMeli commented on docs/website/installation.md
> +### Development Environment
Fix typo from PR #249

2022-08-25 07:57 UTC, allanleal commented
@RMeli , thanks a lot for your contribution. 

>  I open a separate issue for the record?

Yes, please. That would be good.

2022-08-25 07:57 UTC, merged